blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("", ArticlesView.as_view(), name="blog"),
    path("gallery/", gallery_post),
    path("articles/create/", ArticleCreateView.as_view(), name="article_create"),
    path(
        "category/<str:slug>/",
        ArticlesByCategoryView.as_view(),
        name="articles_by_category",
    ),
    path("articles/<str:slug>/", ArticleView.as_view(), name="article"),
    path(
        "articles/<str:slug>/update/",
        ArticleUpdateView.as_view(),
        name="article_update",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main.views import pageNotFound


# Обработка исключения 404
handler404 = pageNotFound


urlpatterns = [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("gallery/", include("gallery.urls", namespace="gallery")),
    path("blog/", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from .views import *

app_name = "gallery"

urlpatterns = [
    path("", GalleryView.as_view(), name="gallery"),
    path("category/<int:pk>/", get_category, name="category"),
]

main/urls.py
from django.urls import path
from .views import *


urlpatterns = [path("", MainView.as_view(), name="main")]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views import View

from utils import DataMixin


# DataMixin - миксин с данными для панели навигации
class MainView(DataMixin, View):
    """
    Представление: отображение основной страницы сайта
    """

    def get(self, request):
        """
        Метод, выполняющийся при GET запросе
        """
        context = self.get_mixin_context(
            title="Александр Донцов"
        )  # Добавление ключа title в контекст
        return render(
            request, "main/main.html", context=context
        )  # Рендер шаблона с необходимым контекстом


def pageNotFound(request, exception):
    """
    Обработка ошибки 404
    """
    return render(
        request=request,
        template_name="main/error404.html",
        status=404,
        context={
            "title": "Страница не найдена: 404",  # Передача в контекст заголовка страницы
            "nav": [
                {"title": "На главную", "url_name": "main"}
            ],  # Передача в контекст навигации (только возврат на главную)
        },
    )

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'main/images/favicon.ico' %}" type="image/x-icon">    
    <link type="text/css" rel="stylesheet" href="{% static 'main/styles/style.css' %}">
    <link rel="stylesheet" href="{% static 'gallery/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'gallery/css/theme.css' %}">
    <script src="{% static 'main/styles/highlight/highlight.js' %}"></script>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}     
    {% bootstrap_javascript %}
    {% bootstrap_messages %}

</head>
<body>
    <div class="container">
        {% include 'main/header.html' %}
        {% block content %}
        {% endblock %}
        {% include 'main/footer.html' %}
    </div>
    {% block scripts %}
    <script src{% static 'main/js/base.js' %}"></script>
    {% endblock %}
    <script src="{% static 'gallery/js/app.js' %}"></script>
    <script src="{% static 'gallery/js/theme.js' %}"></script>
</body>
</html>

main/templates/main/error404.html
{% extends 'main/base.html' %}

{% load static %}


{% block content %}

        <main class="main content--size">
            <h1>Страница не найдена</h1>
            <div class="page404">
                <img src="{% static 'main/images/racoon.gif' %}">
            </div>
        </main>
{% endblock %}

main/templates/main/footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">&copy; 2025 Company, Inc</p>
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
      <ul class="nav col-md-4 justify-content-end">
        {% for n in nav %}
            {% url n.url_name as my_url %}
                <a class="nav-link {% if my_url == request.path or 'blog' in request.path and '/blog/' == my_url %}btn--active{% endif %}" href="{{ my_url }}" target="_self">{{ n.title }}</a>
            {% endfor %}
      </ul>
    </footer>
  </div>

main/templates/main/header.html
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Панель навигации</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'main' %}">Главная</a>
          <a class="nav-link" href="{% url 'gallery:gallery' %}">Галерея фотографий</a>
          <a class="nav-link" href="{% url 'blog' %}">Блог</a>
          <a class="nav-link" href="{% url 'article_create' %}">Добавить статью к блогу</a>
          
        </div>
      </div>
    </div>
  </nav>

main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
        <div class="mt-4 p-5 bg-primary text-white rounded">
            <h1>Порфолио пенсионера</h1>
            <p>Сборник лучших работ специалиста, демонстрирующий его профессионализм,
              таланты и возможности.</p>
              {% comment %} <img src="{% static 'main/images/ya.jpg' %}" class="rounded-circle" alt="..."> {% endcomment %}
          </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'main/js/base.js' %}"></script>
    <script src="{% static 'main/js/main.js' %}"></script>
{% endblock %}

main/templates/main/pagination.html
{% if page_obj.has_other_pages %}
    <nav class="pagination__container">
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page=1">&lt;&lt;</a>
            {% else %}
                <p>&lt;&lt;</p>
            {% endif %}

            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
            {% else %}
                <p>&lt;</p>
            {% endif %}

            {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                    <p class="pagination_active">{{ p }}</p>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <a href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
            {% else %}
                <p>&gt;</p>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ paginator.num_pages }}">&gt;&gt;</a>
            {% else %}
                <p>&gt;&gt;</p>
            {% endif %}
        </div>
    </nav>
{% endif %}